import {
  BarChart3,
  Package,
  ShoppingCart,
  ShieldCheck,
  AlertTriangle,
  FileText,
  Users,
  Truck,
  DollarSign,
  Settings,
  LogOut,
  Plus,
  Search,
  ChevronDown,
  ChevronRight,
  X,
  Check,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Camera,
  Eye,
  Edit3,
  Trash2,
  Download,
  Share2,
  Moon,
  Sun,
  Menu,
  Home,
  ClipboardList,
  TrendingUp,
  TrendingDown,
  Clock,
  Phone,
  Mail,
  MapPin,
  Star,
  Filter,
  Image,
  Zap,
  BadgeCheck,
} from "lucide-react"

export const Icons = {
  dashboard: BarChart3,
  inventory: Package,
  sales: ShoppingCart,
  warranties: ShieldCheck,
  problems: AlertTriangle,
  quotes: FileText,
  customers: Users,
  suppliers: Truck,
  finance: DollarSign,
  settings: Settings,
  logout: LogOut,
  plus: Plus,
  search: Search,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  close: X,
  check: Check,
  alert: AlertCircle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  camera: Camera,
  eye: Eye,
  edit: Edit3,
  trash: Trash2,
  download: Download,
  share: Share2,
  moon: Moon,
  sun: Sun,
  menu: Menu,
  home: Home,
  clipboard: ClipboardList,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  clock: Clock,
  phone: Phone,
  mail: Mail,
  mapPin: MapPin,
  star: Star,
  filter: Filter,
  image: Image,
  zap: Zap,
  badgeCheck: BadgeCheck,
}

export function CategoryIcon({ category, className = "w-5 h-5" }: { category: string; className?: string }) {
  const iconMap: Record<string, React.ReactNode> = {
    iphone: "📱",
    ipad: "📋",
    applewatch: "⌚",
    airpods: "🎧",
    macbook: "💻",
    garmin: "🧭",
  }
  return <span className={className}>{iconMap[category] || "📦"}</span>
}
